### PR TITLE
GetFeedSubmissionResult Endpoint

### PR DESCRIPTION
**Pull request by mirkos93**
I added this missing endpoint. it's my first pull request, I hope I haven't done anything wrong.

### CODE REVIEW

**Comment by krizzdev** [comment]
Hey Mirko. Thanks for your contribution! I will check it late afternoon and respond back :)

**Comment by krizzdev** [comment]
I walked through the code and most parts look pretty good so far. Thank you! What I haven't checked is the response structure. Although the readme.me needs to be updated. Currently I am on vacation until the 17.08. But then I will look at it again and merge it. Have a nice day. 😊

**Comment by rdfito** [comment]
Hi! I am interested in this PR, any update?

**Comment by LooxisDev** [comment]
Hi rdfito, currently I'm migrating our apps to laravel 8. I will look into this PR code while making this package laravel 8 conform. I think I will do it tomorrow. Maybe monday.

**Comment by rdfito** [comment]
Nice! Have a good weekend :)

**Comment by LooxisDev** [comment]
Added readme and merged it. I will release a version for the current Laravel 7.x before I will make a Laravel 8 release.
Have a nice weekend

**Pull request merged**
